name: tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '25 8 * * 1'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Debug with tmate
        type: boolean
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}
